Consider following datasets and do PCA on each datasets.

Datasets: Grocery_std

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("Grocery_std.csv")
df

,Unnamed: 0,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
0,0,0.052933,0.523568,-0.041115,-0.589367,-0.043569,-0.066339
1,1,-0.391302,0.544458,0.170318,-0.270136,0.086407,0.089151
2,2,-0.447029,0.408538,-0.028157,-0.137536,0.133232,2.243293
3,3,0.100111,-0.624020,-0.392977,0.687144,-0.498588,0.093411
4,4,0.840239,-0.052396,-0.079356,0.173859,-0.231918,1.299347
...,...,...,...,...,...,...,...
435,435,1.401312,0.848446,0.850760,2.075222,-0.566831,0.241091
436,436,2.155293,-0.592142,-0.757165,0.296561,-0.585519,0.291501
437,437,0.200326,1.314671,2.348386,-0.543380,2.511218,0.121456
438,438,-0.135384,-0.517536,-0.602514,-0.419441,-0.569770,0.213046
439,439,-0.729307,-0.555924,-0.573227,-0.620094,-0.504888,-0.522869

In [4]:
df.describe()

,Unnamed: 0,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
count,440.000000,4.400000e+02,4.400000e+02,4.400000e+02,4.400000e+02,4.400000e+02,4.400000e+02
mean,219.500000,-3.027881e-17,1.614870e-17,-5.652044e-17,5.652044e-17,4.037175e-17,2.422305e-17
std,127.161315,1.001138e+00,1.001138e+00,1.001138e+00,1.001138e+00,1.001138e+00,1.001138e+00
min,0.000000,-9.496831e-01,-7.787951e-01,-8.373344e-01,-6.283430e-01,-6.044165e-01,-5.402644e-01
25%,109.750000,-7.023339e-01,-5.783063e-01,-6.108364e-01,-4.804306e-01,-5.511349e-01,-3.964005e-01
50%,219.500000,-2.767602e-01,-2.942580e-01,-3.366684e-01,-3.188045e-01,-4.336004e-01,-1.985766e-01
75%,329.250000,3.905226e-01,1.890921e-01,2.849105e-01,9.946441e-02,2.184822e-01,1.048598e-01
max,439.000000,7.927738e+00,9.183650e+00,8.936528e+00,1.191900e+01,7.967672e+00,1.647845e+01

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        440 non-null    int64
 1   Fresh             440 non-null    float64
 2   Milk              440 non-null    float64
 3   Grocery           440 non-null    float64
 4   Frozen            440 non-null    float64
 5   Detergents_Paper  440 non-null    float64
 6   Delicassen        440 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 24.2 KB

In [6]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)
df.columns

Index(['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen'], dtype='object')

In [7]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)

pca.fit(df)

new_component = pca.transform(df)

df['pc'] = new_component

df

,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,pc
0,0.052933,0.523568,-0.041115,-0.589367,-0.043569,-0.066339,0.193291
1,-0.391302,0.544458,0.170318,-0.270136,0.086407,0.089151,0.434420
2,-0.447029,0.408538,-0.028157,-0.137536,0.133232,2.243293,0.811143
3,0.100111,-0.624020,-0.392977,0.687144,-0.498588,0.093411,-0.778648
4,0.840239,-0.052396,-0.079356,0.173859,-0.231918,1.299347,0.166287
...,...,...,...,...,...,...,...
435,1.401312,0.848446,0.850760,2.075222,-0.566831,0.241091,0.870602
436,2.155293,-0.592142,-0.757165,0.296561,-0.585519,0.291501,-0.902520
437,0.200326,1.314671,2.348386,-0.543380,2.511218,0.121456,3.465704
438,-0.135384,-0.517536,-0.602514,-0.419441,-0.569770,0.213046,-0.918023
439,-0.729307,-0.555924,-0.573227,-0.620094,-0.504888,-0.522869,-1.105137